# Generated by Django 5.2 on 2025-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100)),
                ('contract_date', models.DateField()),
                ('partner', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
            ],
        ),
    ]
