# Generated by Django 5.2 on 2025-04-24 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема задачи')),
                ('deadline', models.DateField(verbose_name='Срок выполнения')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('priority', models.TextField(verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='partner',
            field=models.CharField(max_length=255, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='subject',
            field=models.TextField(verbose_name='Предмет договора'),
        ),
    ]
